# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "remix-trial"
client_id = "8fd71a0d9d970607cdf1a1e5ef48570b"
application_url = "https://custom-carrier-shopify-app.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_shipping"

[auth]
redirect_urls = [
  "https://custom-carrier-shopify-app.vercel.app/auth/callback",
  "https://custom-carrier-shopify-app.vercel.app/auth/shopify/callback",
  "https://custom-carrier-shopify-app.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
